title: Welcome to Me Land
author: Sanjay Shanbhag
email: SanjayShanbhag1996@gmail.com
theme: Architect
description: > I am a AI enthusiast always on look out to solve the challenging projects. Eagerness to learn and decipher new skills are my key qualities. On look out for a similar constantly improving and learning environment to work where in  my skills and qualities can further be enhanced.
  

# social links
linkedin_username: https://www.linkedin.com/in/sanjay-shanbhag-2b153b166/
github_username:  Sanjay-Shan

show_excerpts: true # set to false to remove excerpts on the homepage
